INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('3D-udskrivning','https://en.wikipedia.org/wiki/3D_printing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Akrobatik','https://en.wikipedia.org/wiki/Acrobatics' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skuespil','https://en.wikipedia.org/wiki/Acting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Amatørradio','https://en.wikipedia.org/wiki/Amateur_radio' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Animation','https://en.wikipedia.org/wiki/Animation' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Aquascaping','https://en.wikipedia.org/wiki/Aquascaping' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Astrologi','https://en.wikipedia.org/wiki/Astrology' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bagning','https://en.wikipedia.org/wiki/Baking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Baton snurrer','https://en.wikipedia.org/wiki/Baton_twirling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Blogging','https://en.wikipedia.org/wiki/Blogging' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Brætspil','https://en.wikipedia.org/wiki/Board_game' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bogdiskussionsklub','https://en.wikipedia.org/wiki/Book_discussion_club' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gendannelse af bøger','https://en.wikipedia.org/wiki/Book_restoration' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Brasiliansk jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Brødfremstilling','https://en.wikipedia.org/wiki/Breadmaking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bygning','https://en.wikipedia.org/wiki/Building' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cabaret','https://en.wikipedia.org/wiki/Cabaret' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kalligrafi','https://en.wikipedia.org/wiki/Calligraphy' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Lysfremstilling','https://en.wikipedia.org/wiki/Candle_making' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Slikfremstilling','https://en.wikipedia.org/wiki/Candy_making' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bil','https://en.wikipedia.org/wiki/Car');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kortspil','https://en.wikipedia.org/wiki/Card_games' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cardistry','https://en.wikipedia.org/wiki/Cardistry' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ostemagning','https://en.wikipedia.org/wiki/Cheesemaking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rengøring','https://en.wikipedia.org/wiki/Cleaning' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tøj','https://en.wikipedia.org/wiki/Clothing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hjemmelavet kaffe','https://en.wikipedia.org/wiki/Home_roasting_coffee' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Indsamling','https://en.wikipedia.org/wiki/Collecting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Malebog','https://en.wikipedia.org/wiki/Coloring_book' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Computer programmering','https://en.wikipedia.org/wiki/Computer_programming' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Konfekture','https://en.wikipedia.org/wiki/Confectionery' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Madlavning','https://en.wikipedia.org/wiki/Cooking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cosplaying','https://en.wikipedia.org/wiki/Cosplaying' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kuponering','https://en.wikipedia.org/wiki/Couponing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Håndværk','https://en.wikipedia.org/wiki/Craft' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kreativ skrivning','https://en.wikipedia.org/wiki/Creative_writing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hækling','https://en.wikipedia.org/wiki/Crocheting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Korssting','https://en.wikipedia.org/wiki/Cross-stitch' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Krydsogtværs','https://en.wikipedia.org/wiki/Crossword_puzzles' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kryptografi','https://en.wikipedia.org/wiki/Cryptography' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cue sport','https://en.wikipedia.org/wiki/Cue_sports');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dans','https://en.wikipedia.org/wiki/Dance' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Digital kunst','https://en.wikipedia.org/wiki/Digital_art' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Distro-hopping','https://en.wikipedia.org/wiki/Distro-hopping' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Disc-jockey','https://en.wikipedia.org/wiki/Disc-jockey' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gør det selv','https://en.wikipedia.org/wiki/Do_it_yourself' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Drama','https://en.wikipedia.org/wiki/Drama' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tegning','https://en.wikipedia.org/wiki/Drawing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Blandet drik','https://en.wikipedia.org/wiki/Mixed_drink' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Drikker','https://en.wikipedia.org/wiki/Drinking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Elektroniske spil','https://en.wikipedia.org/wiki/Electronic_games' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Elektronik','https://en.wikipedia.org/wiki/Electronics' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Broderi','https://en.wikipedia.org/wiki/Embroidery' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Eksperimenterer','https://en.wikipedia.org/wiki/Experimenting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fantasy sport','https://en.wikipedia.org/wiki/Fantasy_sport' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mode','https://en.wikipedia.org/wiki/Fashion' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mode design','https://en.wikipedia.org/wiki/Fashion_design' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fiskearbejde','https://en.wikipedia.org/wiki/Fishkeeping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Filmfremstilling','https://en.wikipedia.org/wiki/Filmmaking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Blomsterbinding','https://en.wikipedia.org/wiki/Flower_arranging' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fluebinding','https://en.wikipedia.org/wiki/Fly_tying' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Andet sprog erhvervelse','https://en.wikipedia.org/wiki/Second-language_acquisition' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Møbel','https://en.wikipedia.org/wiki/Furniture' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Spil','https://en.wikipedia.org/wiki/Games' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bordspil','https://en.wikipedia.org/wiki/Tabletop_game' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rollespil','https://en.wikipedia.org/wiki/Role-playing_game');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Slægtsforskning','https://en.wikipedia.org/wiki/Genealogy' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Honningkagehus','https://en.wikipedia.org/wiki/Gingerbread_house' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Glasblæsning','https://en.wikipedia.org/wiki/Glassblowing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Grafisk design','https://en.wikipedia.org/wiki/Graphic_design' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gunsmithing','https://en.wikipedia.org/wiki/Gunsmithing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gymnastik','https://en.wikipedia.org/wiki/Gymnastics');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hacker','https://en.wikipedia.org/wiki/Hacker' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Herpetokultur','https://en.wikipedia.org/wiki/Herpetoculture' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hjemmeforbedring','https://en.wikipedia.org/wiki/Home_improvement' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hjemmebrygning','https://en.wikipedia.org/wiki/Homebrewing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Pleje af husplanter','https://en.wikipedia.org/wiki/Houseplant_care' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hula bøjning','https://en.wikipedia.org/wiki/Hula_hooping' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Humor','https://en.wikipedia.org/wiki/Humor' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hydroponics','https://en.wikipedia.org/wiki/Hydroponics' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skøjteløb','https://en.wikipedia.org/wiki/Ice_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Smykkefremstilling','https://en.wikipedia.org/wiki/Jewelry_making' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Puslespil','https://en.wikipedia.org/wiki/Jigsaw_puzzles' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dagbog','https://en.wikipedia.org/wiki/Diary' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Jonglere','https://en.wikipedia.org/wiki/Juggling' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Karaoke','https://en.wikipedia.org/wiki/Karaoke' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Karate','https://en.wikipedia.org/wiki/Karate' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kendama','https://en.wikipedia.org/wiki/Kendama' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Knivfremstilling','https://en.wikipedia.org/wiki/Knife_making' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Strikning','https://en.wikipedia.org/wiki/Knitting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Knude binder','https://en.wikipedia.org/wiki/Knot_tying' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kombucha','https://en.wikipedia.org/wiki/Kombucha' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Blonder','https://en.wikipedia.org/wiki/Lace_making' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Lapidary','https://en.wikipedia.org/wiki/Lapidary' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Læder håndværk','https://en.wikipedia.org/wiki/Leather_crafting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Lego','https://en.wikipedia.org/wiki/Lego' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('musik','https://en.wikipedia.org/wiki/Music' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Podcasts','https://en.wikipedia.org/wiki/Podcasts' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Låseplukning','https://en.wikipedia.org/wiki/Lock_picking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bearbejdning','https://en.wikipedia.org/wiki/Machining' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Macrame','https://en.wikipedia.org/wiki/Macrame' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Magi (illusion)','https://en.wikipedia.org/wiki/Magic_(illusion)' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Makeup','https://en.wikipedia.org/wiki/Makeup' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Labyrint','https://en.wikipedia.org/wiki/Maze' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Metalbearbejdning','https://en.wikipedia.org/wiki/Metalworking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Modelbygning','https://en.wikipedia.org/wiki/Model_building' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Model engineering','https://en.wikipedia.org/wiki/Model_engineering' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Negle kunst','https://en.wikipedia.org/wiki/Nail_art' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Nålepunkt','https://en.wikipedia.org/wiki/Needlepoint' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Origami','https://en.wikipedia.org/wiki/Origami' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Maleri','https://en.wikipedia.org/wiki/Painting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Håndflade','https://en.wikipedia.org/wiki/Palmistry' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Adoption af kæledyr','https://en.wikipedia.org/wiki/Pet_adoption' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Filateli','https://en.wikipedia.org/wiki/Philately' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fotografering','https://en.wikipedia.org/wiki/Photography');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Pilates','https://en.wikipedia.org/wiki/Pilates' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Poi (performance)','https://en.wikipedia.org/wiki/Poi_(performance_art)' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Pole Dancing (siden findes ikke)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Keramik','https://en.wikipedia.org/wiki/Pottery' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kraftløftning','https://en.wikipedia.org/wiki/Powerlifting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Praktiske vittigheder','https://en.wikipedia.org/wiki/Practical_jokes' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Presset blomsterhåndværk','https://en.wikipedia.org/wiki/Pressed_flower_craft');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gåde','https://en.wikipedia.org/wiki/Puzzle' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Quilling','https://en.wikipedia.org/wiki/Quilling' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Quiltning','https://en.wikipedia.org/wiki/Quilting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Quizzer','https://en.wikipedia.org/wiki/Quizzes' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Radiostyret model','https://en.wikipedia.org/wiki/Radio-controlled_model');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Modellering af jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport_modeling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rapping','https://en.wikipedia.org/wiki/Rapping' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Læsning','https://en.wikipedia.org/wiki/Reading');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Efterbehandling','https://en.wikipedia.org/wiki/Refinishing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Reiki','https://en.wikipedia.org/wiki/Reiki' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Robotkamp','https://en.wikipedia.org/wiki/Robot_combat' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rubiks terning','https://en.wikipedia.org/wiki/Rubik%27s_Cube' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Scrapbooking','https://en.wikipedia.org/wiki/Scrapbooking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('SCUBA Dykning','https://en.wikipedia.org/wiki/SCUBA_Diving' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Modellering','https://en.wikipedia.org/wiki/Sculpting' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Syning','https://en.wikipedia.org/wiki/Sewing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skomageri','https://en.wikipedia.org/wiki/Shoemaking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Synger','https://en.wikipedia.org/wiki/Singing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skitse (tegning)','https://en.wikipedia.org/wiki/Sketch_(drawing)' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sjippetov','https://en.wikipedia.org/wiki/Skipping_rope');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Slot bil','https://en.wikipedia.org/wiki/Slot_car');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sæbefremstilling','https://en.wikipedia.org/wiki/Soapmaking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sociale medier','https://en.wikipedia.org/wiki/Social_media' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Regneark','https://en.wikipedia.org/wiki/Spreadsheets' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Stand-up','https://en.wikipedia.org/wiki/Stand-up_comedy' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Frimærkesamling','https://en.wikipedia.org/wiki/Stamp_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bordtennis','https://en.wikipedia.org/wiki/Table_tennis');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tarot','https://en.wikipedia.org/wiki/Tarot' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Taksidermi','https://en.wikipedia.org/wiki/Taxidermy' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Velgørenhedsbutik','https://en.wikipedia.org/wiki/Charity_shop' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Videoredigering','https://en.wikipedia.org/wiki/Video_editing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Udvikling af videospil','https://en.wikipedia.org/wiki/Video_game_development' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Videospil','https://en.wikipedia.org/wiki/Video_gaming' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Videografi','https://en.wikipedia.org/wiki/Videography');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Virtual reality','https://en.wikipedia.org/wiki/Virtual_reality' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Film','https://en.wikipedia.org/wiki/Movies' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tv-program','https://en.wikipedia.org/wiki/Television_program' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Voksning','https://en.wikipedia.org/wiki/Waxing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vævning','https://en.wikipedia.org/wiki/Weaving' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Webtoon','https://en.wikipedia.org/wiki/Webtoon' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vægt træning','https://en.wikipedia.org/wiki/Weight_training');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Svejsning','https://en.wikipedia.org/wiki/Welding' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hviskende','https://en.wikipedia.org/wiki/Whittling' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vinfremstilling','https://en.wikipedia.org/wiki/Winemaking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Træskæring','https://en.wikipedia.org/wiki/Wood_carving' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Træbearbejdning','https://en.wikipedia.org/wiki/Woodworking' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ordsøgninger','https://en.wikipedia.org/wiki/Word_searches' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Verdensbygning','https://en.wikipedia.org/wiki/Worldbuilding' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skrivning','https://en.wikipedia.org/wiki/Writing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Yo-yoing','https://en.wikipedia.org/wiki/Yo-yoing' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Yoga','https://en.wikipedia.org/wiki/Yoga' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Zumba','https://en.wikipedia.org/wiki/Zumba' );
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Luftsport','https://en.wikipedia.org/wiki/Air_sports');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Airsoft','https://en.wikipedia.org/wiki/Airsoft');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Amatørgeologi','https://en.wikipedia.org/wiki/Amateur_geology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Forlystelsespark','https://en.wikipedia.org/wiki/Amusement_park');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bueskydning','https://en.wikipedia.org/wiki/Archery');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Astronomi','https://en.wikipedia.org/wiki/Astronomy');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Backpacking (vildmark)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Badminton','https://en.wikipedia.org/wiki/Badminton');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Base jumping','https://en.wikipedia.org/wiki/BASE_jumping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Baseball','https://en.wikipedia.org/wiki/Baseball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Basketball','https://en.wikipedia.org/wiki/Basketball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Biavl','https://en.wikipedia.org/wiki/Beekeeping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fuglekiggeri','https://en.wikipedia.org/wiki/Birdwatching');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Smedarbejde','https://en.wikipedia.org/wiki/Blacksmithing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('BMX','https://en.wikipedia.org/wiki/BMX');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Brætsport','https://en.wikipedia.org/wiki/Board_sports');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bodybuilding','https://en.wikipedia.org/wiki/Bodybuilding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bonsai','https://en.wikipedia.org/wiki/Bonsai');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sommerfugletur','https://en.wikipedia.org/wiki/Butterfly_watching');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bus','https://en.wikipedia.org/wiki/Bus');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Camping','https://en.wikipedia.org/wiki/Camping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kanosejlads','https://en.wikipedia.org/wiki/Canoeing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Canyoning','https://en.wikipedia.org/wiki/Canyoning');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Huleforskning','https://en.wikipedia.org/wiki/Caving');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kompostering','https://en.wikipedia.org/wiki/Composting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cykling','https://en.wikipedia.org/wiki/Cycling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dowsing','https://en.wikipedia.org/wiki/Dowsing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kørsel','https://en.wikipedia.org/wiki/Driving');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Landbrug','https://en.wikipedia.org/wiki/Farming');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fiskeri','https://en.wikipedia.org/wiki/Fishing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Flag fodbold','https://en.wikipedia.org/wiki/Flag_football');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Blomst','https://en.wikipedia.org/wiki/Flower');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Luftfart','https://en.wikipedia.org/wiki/Aviation');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Flyvende skive','https://en.wikipedia.org/wiki/Flying_disc');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Foder','https://en.wikipedia.org/wiki/Foraging');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fossicking','https://en.wikipedia.org/wiki/Fossicking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Freestyle fodbold','https://en.wikipedia.org/wiki/Freestyle_football');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Havearbejde','https://en.wikipedia.org/wiki/Gardening');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Geocaching','https://en.wikipedia.org/wiki/Geocaching');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Spøgelsesjagt','https://en.wikipedia.org/wiki/Ghost_hunting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Guldprospektering','https://en.wikipedia.org/wiki/Gold_prospecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Graffiti','https://en.wikipedia.org/wiki/Graffiti');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Håndbold','https://en.wikipedia.org/wiki/Handball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Naturlægemidler','https://en.wikipedia.org/wiki/Herbalism');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Herping','https://en.wikipedia.org/wiki/Herping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Højeffektiv raket','https://en.wikipedia.org/wiki/High-power_rocketry');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vandreture','https://en.wikipedia.org/wiki/Hiking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hobby hest','https://en.wikipedia.org/wiki/Hobby_horse');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hobby tunneling','https://en.wikipedia.org/wiki/Hobby_tunneling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hooping','https://en.wikipedia.org/wiki/Hooping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ridning','https://en.wikipedia.org/wiki/Horseback_riding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Jagt','https://en.wikipedia.org/wiki/Hunting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('In-line skating','https://en.wikipedia.org/wiki/Inline_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Løbe','https://en.wikipedia.org/wiki/Jogging');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ro kajak','https://en.wikipedia.org/wiki/Kayaking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Glente','https://en.wikipedia.org/wiki/Kite');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kitesurfing','https://en.wikipedia.org/wiki/Kitesurfing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Lacrosse','https://en.wikipedia.org/wiki/Lacrosse');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('LARPing','https://en.wikipedia.org/wiki/LARPing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Letterboxing (hobby)','https://en.wikipedia.org/wiki/Letterboxing_(hobby)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kampsport','https://en.wikipedia.org/wiki/Martial_arts');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Metaldetektor','https://en.wikipedia.org/wiki/Metal_detector');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Meteorologi','https://en.wikipedia.org/wiki/Meteorology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Motorsport','https://en.wikipedia.org/wiki/Motor_sports');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mountainbiking','https://en.wikipedia.org/wiki/Mountain_biking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bjergbestigning','https://en.wikipedia.org/wiki/Mountaineering');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Museum','https://en.wikipedia.org/wiki/Museum');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Svampejagt','https://en.wikipedia.org/wiki/Mushroom_hunting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mykologi','https://en.wikipedia.org/wiki/Mycology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Netball','https://en.wikipedia.org/wiki/Netball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Nordisk skøjteløb','https://en.wikipedia.org/wiki/Nordic_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Orientering','https://en.wikipedia.org/wiki/Orienteering');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Paintball','https://en.wikipedia.org/wiki/Paintball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Parkour','https://en.wikipedia.org/wiki/Parkour');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Podcast','https://en.wikipedia.org/wiki/Podcast');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Polo','https://en.wikipedia.org/wiki/Polo');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Offentlig transport','https://en.wikipedia.org/wiki/Public_transport');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rafting','https://en.wikipedia.org/wiki/Rafting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Jernbane','https://en.wikipedia.org/wiki/Railway');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rappellering','https://en.wikipedia.org/wiki/Rappelling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Road Cykling','https://en.wikipedia.org/wiki/Road_Cycling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rulleskøjteløb','https://en.wikipedia.org/wiki/Roller_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rugby fodbold','https://en.wikipedia.org/wiki/Rugby_football');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Løb','https://en.wikipedia.org/wiki/Running');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sejler','https://en.wikipedia.org/wiki/Sailing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sand kunst og leg','https://en.wikipedia.org/wiki/Sand_art_and_play');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Spejder','https://en.wikipedia.org/wiki/Scouting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dykning','https://en.wikipedia.org/wiki/Scuba_diving');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sculling','https://en.wikipedia.org/wiki/Sculling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Roning (sport)','https://en.wikipedia.org/wiki/Rowing_(sport)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Optagelse','https://en.wikipedia.org/wiki/Shooting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Handle ind','https://en.wikipedia.org/wiki/Shopping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Shuffleboard','https://en.wikipedia.org/wiki/Shuffleboard');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skateboarding','https://en.wikipedia.org/wiki/Skateboarding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Stå på ski','https://en.wikipedia.org/wiki/Skiing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skimboarding','https://en.wikipedia.org/wiki/Skimboarding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Faldskærmsudspring','https://en.wikipedia.org/wiki/Skydiving');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Slacklining','https://en.wikipedia.org/wiki/Slacklining');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Snowboarding','https://en.wikipedia.org/wiki/Snowboarding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Snescooterkørsel','https://en.wikipedia.org/wiki/Snowmobiling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Snesko','https://en.wikipedia.org/wiki/Snowshoeing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fodbold','https://en.wikipedia.org/wiki/Soccer');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sten springer over','https://en.wikipedia.org/wiki/Stone_skipping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Solbadning','https://en.wikipedia.org/wiki/Sun_bathing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Surfing','https://en.wikipedia.org/wiki/Surfing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Overlevelse','https://en.wikipedia.org/wiki/Survivalism');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Menneskelig svømning','https://en.wikipedia.org/wiki/Human_swimming');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Taekwondo','https://en.wikipedia.org/wiki/Taekwondo');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tai Chi','https://en.wikipedia.org/wiki/Tai_chi');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tennis','https://en.wikipedia.org/wiki/Tennis');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Topiary','https://en.wikipedia.org/wiki/Topiary');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Turisme','https://en.wikipedia.org/wiki/Tourism');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gennem vandring','https://en.wikipedia.org/wiki/Thru-hiking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Messe','https://en.wikipedia.org/wiki/Trade_fair');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rejse','https://en.wikipedia.org/wiki/Travel');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Byudforskning','https://en.wikipedia.org/wiki/Urban_exploration');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ferie','https://en.wikipedia.org/wiki/Vacation');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vegetabilsk landbrug','https://en.wikipedia.org/wiki/Vegetable_farming');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Restaurering af køretøjet','https://en.wikipedia.org/wiki/Vehicle_restoration');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gå','https://en.wikipedia.org/wiki/Walking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vandsport','https://en.wikipedia.org/wiki/Water_sports');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Biologi','https://en.wikipedia.org/wiki/Biology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kemi','https://en.wikipedia.org/wiki/Chemistry');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Elektrokemi','https://en.wikipedia.org/wiki/Electrochemistry');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Geografi','https://en.wikipedia.org/wiki/Geography');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Historie','https://en.wikipedia.org/wiki/History');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Matematik','https://en.wikipedia.org/wiki/Mathematics');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Psykologi','https://en.wikipedia.org/wiki/Psychology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fysik','https://en.wikipedia.org/wiki/Physics');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Videnskab og teknologi studier','https://en.wikipedia.org/wiki/Science_and_technology_studies');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sociale Studier','https://en.wikipedia.org/wiki/Social_studies');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sportsvidenskab','https://en.wikipedia.org/wiki/Sports_science');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Action figur','https://en.wikipedia.org/wiki/Action_figure');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Antikviteter','https://en.wikipedia.org/wiki/Antiquing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ant-holder','https://en.wikipedia.org/wiki/Ant-keeping');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kunstindsamling','https://en.wikipedia.org/wiki/Art_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bogindsamling','https://en.wikipedia.org/wiki/Book_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Knapopsamling','https://en.wikipedia.org/wiki/Button_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bytte kort','https://en.wikipedia.org/wiki/Trading_cards');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Møntindsamling','https://en.wikipedia.org/wiki/Coin_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tegneserieindsamling','https://en.wikipedia.org/wiki/Comic_book_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Deltiologi','https://en.wikipedia.org/wiki/Deltiology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Die-cast legetøj','https://en.wikipedia.org/wiki/Die-cast_toy');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Digital hamstring','https://en.wikipedia.org/wiki/Digital_hoarding');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dukker','https://en.wikipedia.org/wiki/Dolls');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Elementindsamling','https://en.wikipedia.org/wiki/Element_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Flygtig','https://en.wikipedia.org/wiki/Ephemera');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Telefonkort','https://en.wikipedia.org/wiki/Telephone_card');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Knivopsamling','https://en.wikipedia.org/wiki/Knife_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Lotologi','https://en.wikipedia.org/wiki/Lotology');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Film memorabilia','https://en.wikipedia.org/wiki/Film_memorabilia');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fingeraftryk','https://en.wikipedia.org/wiki/Fingerprint');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Parfume','https://en.wikipedia.org/wiki/Perfume');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Phillumeny','https://en.wikipedia.org/wiki/Phillumeny');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Pladesamling','https://en.wikipedia.org/wiki/Record_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rock tumbling','https://en.wikipedia.org/wiki/Rock_tumbling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Patch indsamling','https://en.wikipedia.org/wiki/Patch_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sko','https://en.wikipedia.org/wiki/Shoes');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sportsmemorabilia','https://en.wikipedia.org/wiki/Sports_memorabilia');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tøjdyr','https://en.wikipedia.org/wiki/Stuffed_toy');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Te pose','https://en.wikipedia.org/wiki/Tea_bag');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Billet (adgang)','https://en.wikipedia.org/wiki/Ticket_(admission)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Legetøj','https://en.wikipedia.org/wiki/Toys');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Transitkort','https://en.wikipedia.org/wiki/Transit_map');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Samling af videospil','https://en.wikipedia.org/wiki/Video_game_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vintage biler','https://en.wikipedia.org/wiki/Vintage_cars');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vintage tøj','https://en.wikipedia.org/wiki/Vintage_clothing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vinylplader','https://en.wikipedia.org/wiki/Vinyl_Records');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Auto audiophilia','https://en.wikipedia.org/wiki/Auto_audiophilia');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fossil jagt','https://en.wikipedia.org/wiki/Fossil_hunting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Insektindsamling','https://en.wikipedia.org/wiki/Insect_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Magnetfiskeri','https://en.wikipedia.org/wiki/Magnet_fishing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Metaldetektering','https://en.wikipedia.org/wiki/Metal_detecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mineralindsamling','https://en.wikipedia.org/wiki/Mineral_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Stenbalancering','https://en.wikipedia.org/wiki/Rock_balancing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Havglas','https://en.wikipedia.org/wiki/Sea_glass');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Muslingeskal','https://en.wikipedia.org/wiki/Seashell');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Stenopsamling','https://en.wikipedia.org/wiki/Stone_collecting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dyrepleje','https://en.wikipedia.org/wiki/Animal_fancy');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Øksekast','https://en.wikipedia.org/wiki/Axe_throwing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Backgammon','https://en.wikipedia.org/wiki/Backgammon');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skønhedskonkurrence','https://en.wikipedia.org/wiki/Beauty_pageant');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Boksning','https://en.wikipedia.org/wiki/Boxing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kontraktsbro','https://en.wikipedia.org/wiki/Contract_Bridge');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kladder','https://en.wikipedia.org/wiki/Draughts');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cheerleading','https://en.wikipedia.org/wiki/Cheerleading');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skak','https://en.wikipedia.org/wiki/Chess');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Farvebeskyttelse (flag spinding)','https://en.wikipedia.org/wiki/Color_guard_(flag_spinning)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cribbage','https://en.wikipedia.org/wiki/Cribbage');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Curling','https://en.wikipedia.org/wiki/Curling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Konkurrencedygtig dans','https://en.wikipedia.org/wiki/Competitive_dance');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dart','https://en.wikipedia.org/wiki/Darts');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Debat','https://en.wikipedia.org/wiki/Debate');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Dominoer','https://en.wikipedia.org/wiki/Dominoes');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Konkurrencedygtig spisning','https://en.wikipedia.org/wiki/Competitive_eating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Esports','https://en.wikipedia.org/wiki/Esports');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hegn','https://en.wikipedia.org/wiki/Fencing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gå (spil)','https://en.wikipedia.org/wiki/Go_(game)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ishockey','https://en.wikipedia.org/wiki/Ice_hockey');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Judo','https://en.wikipedia.org/wiki/Judo');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Jujitsu','https://en.wikipedia.org/wiki/Jujitsu');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kabaddi','https://en.wikipedia.org/wiki/Kabaddi');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ordspil','https://en.wikipedia.org/wiki/Word_games');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Lasermærke','https://en.wikipedia.org/wiki/Laser_tag');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mahjong','https://en.wikipedia.org/wiki/Mahjong');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kugler','https://en.wikipedia.org/wiki/Marbles');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Model FN','https://en.wikipedia.org/wiki/Model_United_Nations');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Poker','https://en.wikipedia.org/wiki/Poker');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Pool (cue sports)','https://en.wikipedia.org/wiki/Pool_(cue_sports)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Shogi','https://en.wikipedia.org/wiki/Shogi');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Slot bilspil','https://en.wikipedia.org/wiki/Slot_car_racing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hurtigkubning','https://en.wikipedia.org/wiki/Speedcubing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Sport stabling','https://en.wikipedia.org/wiki/Sport_stacking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bordfodbold','https://en.wikipedia.org/wiki/Table_football');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Volleyball','https://en.wikipedia.org/wiki/Volleyball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Brydning','https://en.wikipedia.org/wiki/Wrestling');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Association fodbold','https://en.wikipedia.org/wiki/Association_football');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Australsk spiller fodbold','https://en.wikipedia.org/wiki/Australian_rules_football');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bilsport','https://en.wikipedia.org/wiki/Auto_racing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Beach Volleyball','https://en.wikipedia.org/wiki/Beach_volleyball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Breakdancing','https://en.wikipedia.org/wiki/Breakdancing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Klatring','https://en.wikipedia.org/wiki/Climbing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Cricket','https://en.wikipedia.org/wiki/Cricket');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Croquet','https://en.wikipedia.org/wiki/Croquet');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Disc golf','https://en.wikipedia.org/wiki/Disc_golf');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hundesport','https://en.wikipedia.org/wiki/Dog_sport');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Udstillingsøvelse','https://en.wikipedia.org/wiki/Exhibition_drill');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Field hockey','https://en.wikipedia.org/wiki/Field_hockey');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kunstskøjteløb','https://en.wikipedia.org/wiki/Figure_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fodtaske','https://en.wikipedia.org/wiki/Footbag');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Frisbee','https://en.wikipedia.org/wiki/Frisbee');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Golf','https://en.wikipedia.org/wiki/Golf');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hestesko','https://en.wikipedia.org/wiki/Horseshoes');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Isbåd','https://en.wikipedia.org/wiki/Iceboat');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Jukskei','https://en.wikipedia.org/wiki/Jukskei');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kart racing','https://en.wikipedia.org/wiki/Kart_racing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Knivkastning','https://en.wikipedia.org/wiki/Knife_throwing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Langdistanceløb','https://en.wikipedia.org/wiki/Long-distance_running');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Marcherende band','https://en.wikipedia.org/wiki/Marching_band');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Modelfly','https://en.wikipedia.org/wiki/Model_aircraft');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Pickleball','https://en.wikipedia.org/wiki/Pickleball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Quidditch (sport)','https://en.wikipedia.org/wiki/Quidditch_(sport)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Race gåtur','https://en.wikipedia.org/wiki/Race_walking');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Racquetball','https://en.wikipedia.org/wiki/Racquetball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Radiostyret bil','https://en.wikipedia.org/wiki/Radio-controlled_car');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Roller derby','https://en.wikipedia.org/wiki/Roller_derby');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Rugby liga','https://en.wikipedia.org/wiki/Rugby_league');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Roning','https://en.wikipedia.org/wiki/Rowing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Skydesport','https://en.wikipedia.org/wiki/Shooting_sport');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Slædehundevæddeløb','https://en.wikipedia.org/wiki/Sled_dog_racing');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Softball','https://en.wikipedia.org/wiki/Softball');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Hurtigløb på skøjter','https://en.wikipedia.org/wiki/Speed_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Squash (sport)','https://en.wikipedia.org/wiki/Squash_(sport)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tennispolo','https://en.wikipedia.org/wiki/Tennis_polo');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Fastgør bil','https://en.wikipedia.org/wiki/Tether_car');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Tour skøjteløb','https://en.wikipedia.org/wiki/Tour_skating');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Trapshooting','https://en.wikipedia.org/wiki/Trapshooting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Triatlon','https://en.wikipedia.org/wiki/Triathlon');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Ultimate (sport)','https://en.wikipedia.org/wiki/Ultimate_(sport)');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Vandpolo','https://en.wikipedia.org/wiki/Water_polo');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Læring','https://en.wikipedia.org/wiki/Learning');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Meditation','https://en.wikipedia.org/wiki/Meditation');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Mikroskopi','https://en.wikipedia.org/wiki/Microscopy');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Forskning','https://en.wikipedia.org/wiki/Research');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Kortbølgelytning','https://en.wikipedia.org/wiki/Shortwave_listening');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Audiofil','https://en.wikipedia.org/wiki/Audiophile');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Flyspotting','https://en.wikipedia.org/wiki/Aircraft_spotting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Amatør astronomi','https://en.wikipedia.org/wiki/Amateur_astronomy');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Bus spotting','https://en.wikipedia.org/wiki/Bus_spotting');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Gongoozler','https://en.wikipedia.org/wiki/Gongoozler');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Satellitovervågning','https://en.wikipedia.org/wiki/Satellite_watching');
INSERT INTO HOBBY (NAME,DESCRIPTION) VALUES ('Trainspotting (hobby)','https://en.wikipedia.org/wiki/Trainspotting_(hobby)');